### PR TITLE
[WIP] Additional start script support

### PR DESCRIPTION
**Pull request by kkellerlbl**
These changes add support for starting multiple API services in the current kbase deploy environments.  Most notable is adding a stanza in deployment.cfg for each service API.

One possible issue is that the global deployment.cfg files in each environment (-ci, -next, prod) use the same stanza names for each service.  So the name of the stanza in -ci would not be data_api.kbase.ci, but data_api.kbase.us (the changes in scripts/start_service support this).  If the services are being started in Travis without using scripts/start_service then this change shouldn't break that.  If there's a better way of dealing with this issue let me know, because I'm not totally happy with the way I have it at the moment.  I have tested what I have in my own environment and it does behave as I'd expect it to in a -ci deploy.

### CODE REVIEW

**Comment by mlhenderson** [comment]
Take a look at PR 108.  I think most of what you have should be compatible, but for anything that is not we should try to converge on something.

**Comment by kkellerlbl** [comment]
I'm still pretty wonked.  I'll look at it soon and make changes to this PR if needed.

**Comment by mlhenderson** [comment]
108 was merged to develop after I had Dan review it, so no problem.  Once you merge in updates from develop this should be easy to get through.  It looks like the only thing that will change here is the lines for deployment.cfg, just need to add pidfile entries to the latest deployment.cfg and you'll be good.  Apparently I neglected to do that in my PR.

**Comment by kkellerlbl** [comment]
I'm going to merge develop against my fork, reconcile any changes, then do a new PR for start script support.

**Pull request closed without merging**
