### PR TITLE
Refactor towards thrift services/clients

### PR DESCRIPTION
**Pull request by mlhenderson**
Changes:

* renamed from biokbase to doekbase
* More than 100 unit tests for taxon, assembly, genome_annotation for new and old data.
* Thrift service code for taxon
* Refactored assembly, taxon, genome_annotation in prep for thrift service interfaces
* More organization into directories
* Bugfixes for wsfile stand-in

### CODE REVIEW

**Comment by dangunter** [comment]
why did wsmock.py get reinstated? that got replaced by wsfile.py

**Comment by mlhenderson** [comment]
Probably something I missed when I did the merge.  I can rip it out, no
problem.

**Comment by dangunter** [comment]
also, I looked at Jenkins and it is not trying to run from the file workspace even when the tests are given the --ws-url=<path>. I wonder what happened there?

**Comment by mlhenderson** [comment]
I can try to troubleshoot that more, but I reverted the @skipUnless, the
workspace dicts you were setting didn't match up with how the tests were
configured to run.
You did want this merge today, right?

**Comment by dangunter** [comment]
Maybe we should try to do these merges in smaller pieces. It looks like
I'll have to go back and re-do a bunch of stuff now, because this thing is
"too big to fail".

**Pull request merged**
