### PR TITLE
More detailed service logging

### PR DESCRIPTION
**Pull request by dangunter**
JIRA https://atlassian.kbase.us/browse/KBASE-3274

- [x] Add new log messages
- [x] Add log config to data_api_start_service.py options
- [x] Refactor services to use the same code at init and wrapping each method
- [x] Add tests for refactored new module (doekbase.data_api.service_core)

### CODE REVIEW

**Comment by danielolson5** [comment]
Is this using the kbase logging library?

https://github.com/kbase/kbapi_common/blob/master/lib/biokbase/log.py

**Comment by dangunter** [comment]
no, that doesn't seem to add much besides syslog (which is configurable via the .conf file), and would break local and TravisCI debugging, which is the raison d'etre for these changes.

**Comment by danielolson5** [comment]
We have tried to integrate that logging library as widely as possible to have a uniform log format, and a single point to control that format, and for future maintainability.  

What about that library makes it break travis and local debugging?  Any idea on the effort required to make it meet thise requirements?

**Comment by dangunter** [comment]
I don't mind changing the format to be whatever you are using, which would address your concern. Where is that documented?

**Comment by dangunter** [comment]
@kkellerlbl this is ready for review (you seemed inclined) -- after we are all "back" of course!

**Pull request merged**
