### PR TITLE
[WIP] get_features type fix

### PR DESCRIPTION
**Pull request by kkellerlbl**
Please do not merge yet!

This PR will be to try to address KBASE-3172.  I will add mocks for how the code could work and ask for comments.

### CODE REVIEW

**Comment by kkellerlbl** [comment]
This is a Python translation of what I think the thrift spec I wrote in the jira ticket would look like.  I am not sure it's what people are asking for though.  Pretend that if there's an mRNA feature associated with these dummy features, it doesn't get returned.

result = api.get_features(types=['CDS','gene'],feature_ids=['kb|x.CDS.y', 'kb|x.gene.z'])
print result
{'kb|g.x.CDS.y': 
  {
    'CDS':
      {'feature_id':'kb|g.x.CDS.y', 'feature_function': ...}, 
    'gene':
      {'feature_id': 'kb|g.x.gene.m': ...}
  },
  'kb|g.x.gene.z':
  {
    'CDS':
      {'feature_id':'kb|g.x.CDS.n', 'feature_function': ...}, 
    'gene':
      {'feature_id': 'kb|g.x.gene.z': ...}
  }
}

**Comment by kkellerlbl** [comment]
After talking with Jason and Marcin, I think we have a better idea for the return structure.

    result = api.get_features(types=['CDS','gene'],feature_ids=['cdsid1', 'geneid2'])
    print result
    {
      'geneid2': 
      [
          {'feature_id':'cdsid3', 'feature_type': 'CDS','feature_function': ...}, 
          {'feature_id': 'geneid2': 'feature_type': 'gene', .... }
      ],
      'cdsid1':
      [
          {'feature_id':'cdsid1', 'feature_type': 'CDS', 'feature_function': ...}, 
          {'feature_id': 'geneid4': 'feature_type': 'gene', ....}
      ]
    }

Having a list means that if you do result = api.get_features(types=['CDS'],feature_ids=['cdsid1', 'cdsid2']) then you can always look only at result[key][0].  And if you don't submit a types list, meaning you want every feature that matches the CDS, then you very likely want every feature anyway and need to look at every feature in the list (e.g., you're doing a track browser).  This comes with the drawback that if you make the first call above where types=['CDS','gene'], you may get unwanted information and you have to inspect every feature in the list to see which one you want, whereas with the tuple substructure you could simply ignore the types you don't want.

By the same reasoning, to optimize making it easy to call the function for the common use cases of 1) I want only one type, or 2) I want all types, I'm leaving the inputs the same, because in both cases, I will probably generate a list from get_feature_ids and not want to have to generate a list of tuples where every type is the same.

The tuple-style would make the return result nonredundant:

    result = api.get_features( [ {'cdsid1','CDS'}, {'geneid2','gene'} ] )

But I think the benefits of not having to make these tuples in the common cases outweighs the drawbacks.

Comments?

**Comment by kkellerlbl** [comment]
The new proposed Thrift spec.  No new Feature_data_by_type object should be needed (woo-hoo!), so it's just a change to the get_features() spec.

    map<string,list<Feature_data>> get_features(1:required string token,
      2:required ObjectReference ref,
      3:list<string> feature_type_list,
      4:list<string> feature_id_list) throws ( ....

**Comment by kkellerlbl** [comment]
If no feature_type_list is provided, return all types.  If no feature_id_list is provided return all features.

**Comment by kkellerlbl** [comment]
My get_feature_ids() - strand bugfix is also in here.  When pull #132 is merged it should make that redundant.

**Comment by mlhenderson** [comment]
How does this reconcile with how get_feature_ids() works currently?

Why not duplicate the interface for get_feature_ids()?  You could then just internally call get_feature_ids to do the filtering and then fetch only that data.  You basically have to duplicate this kind of logic anyway, so why not take advantage of the code that already does this?

The only remaining item then would be to decide what format the ids should be given in.  We could accept the output of get_feature_ids() as the input format for get_features(), meaning instead of a list you pass in the dictionary returned by get_feature_ids() and we deal with that.  This would at least be internally consistent, and then you could preserve method chaining.

Example:
(assuming you got back your feature ids from somewhere other than get_feature_ids())
result = api.get_features(feature_ids={"gene": ['geneid2'], "CDS": ['cdsid1']})
print result
{
  'geneid2': 
      {'feature_id': 'geneid2': 'feature_type': 'gene', .... }
  'cdsid1':
      {'feature_id':'cdsid1', 'feature_type': 'CDS', 'feature_function': ...}
}

(if you used get_feature_ids())
result = api.get_features(feature_ids=api.get_feature_ids(filters={"type_list": ["gene", "CDS"]})["by_type"])

**Comment by kkellerlbl** [comment]
From what I could tell looking at the thrift specs, the code, and example returns from get_feature_ids(), get_features() currently can't accept the output from get_feature_ids() in general, since in some cases get_feature_ids() returns a dict, but get_features() requires a list as input.  And I think that the output for group_by options like by_region is also more complex than just {key:[ids]}, so the structure is a little different from the other group_by structures (I didn't look at that as carefully though).  It might be possible to reconcile all of the group_by formats so that get_features() could operate on any possible get_feature_ids() output, but I was planning on only addressing the issue Jason found, in order to save time.

Alternatively, if get_feature_ids() group_by region is supposed to be returning a dict with the values as a list, and not a more complex structure, then we can make sure it does that in all cases, and then it'd be easier (probably a lot easier but that's just a hunch) to make get_features() be able to take get_feature_ids() output as input.

Tomorrow I can reproduce all the possible outputs that get_feature_ids() emits so we can compare them.

**Comment by mlhenderson** [comment]
Sorry, but I will not be in favor of quick fixes here, this has to be done correctly.  Let's determine first what the right thing to do is, and then we can worry about time.  I'll make the changes if needed.

**Comment by kkellerlbl** [comment]
Ha, I got get_feature_ids() grouped by region earlier this week.  Here's what that output looked like (from Slack).

    {'by_region': 
        {'kb|g.166819.c.0': 
            {'+': 
                {'1002883-1004221': ['kb|g.166819.mRNA.743', 'kb|g.166819.CDS.713', 'kb|g.166819.locus.886'],
                '1002088-1002643': ['kb|g.166819.locus.516', 'kb|g.166819.mRNA.649', 'kb|g.166819.CDS.637'],
                '1004617-1005487': ['kb|g.166819.mRNA.57', 'kb|g.166819.CDS.262', 'kb|g.166819.locus.73'],
                '1006886-1009535': ['kb|g.166819.locus.186', 'kb|g.166819.CDS.183', 'kb|g.166819.mRNA.276']
                },
            '-': 
                {'1010461-1010670': ['kb|g.166819.mRNA.61'],
                '1001186-1001957': ['kb|g.166819.mRNA.263', 'kb|g.166819.locus.166', 'kb|g.166819.CDS.41'],
                '1000296-1001148': ['kb|g.166819.locus.122', 'kb|g.166819.CDS.133', 'kb|g.166819.mRNA.301'],
                '1006208-1006898': ['kb|g.166819.locus.987', 'kb|g.166819.mRNA.706', 'kb|g.166819.CDS.748'],
                '1010461-1011308': ['kb|g.166819.locus.142'],
                '1010097-1010580': ['kb|g.166819.CDS.135', 'kb|g.166819.mRNA.61'],
                '1010396-1010540': ['kb|g.166819.CDS.135']
                }
            }
        }
    }

One compromise that would be easy would be to make get_features() take the output that get_feature_ids() emits with group_by=type.  This way that can still be chained without having to modify get_feature_ids() now, and later we can work on making get_features() work with get_feature_ids() in more cases.

I just saw your comment but I'm going to post this first.

**Comment by kkellerlbl** [comment]
I can do the changes, it just means I'd spend less time on other tasks (like the Perl docs or more rigorous testing).  If you really do have the time for these (which you're not supposed to, you're supposed to be on leave!) that's great too.  (We can also tag-team; you could work on fixing the get_feature_ids() output and I could work on fixing get_features().)

**Comment by kkellerlbl** [comment]
FWIW my preference is that get_features() doesn't have to try to figure out the structure of its inputs before proceeding; I feel like that introduces too much complexity.

**Comment by kkellerlbl** [comment]
Jason pointed out that the default structure for the get_features_id() default group_by (by type) does have a "by_type" key, so we'd potentially want get_features() to take an input structure like this:

    { "by_type": {"gene": ['geneid2'], "CDS": ['cdsid1']} }

**Comment by mlhenderson** [comment]
So then accepting a list of tuples would solve that, which would mean
get_feature_ids() output would change.  Let's write out some examples fully
to see what everything would look like before we change code or thrift
specs.

**Comment by kkellerlbl** [comment]
Okay!  We talked after our standup, and we have agreement on inputs and outputs that's expressive enough for what we need while minimizing the changes needed.

get_features() will take as input a list of tuples:
    [ ('gene', 'featureid1'), ('CDS','featureid2'), ('typeN','featureidN'), ... ]

It should support 'all' as a wildcard type.

In addition, get_feature_ids() will return as output, instead of a list of feature ids, a list of feature tuples.  So, for example, the by_region output will now be (much truncated):

    {'by_region': 
        {'kb|g.166819.c.0': 
            {'+': 
                {'1002883-1004221': [ ('mRNA', 'kb|g.166819.mRNA.743'), ('CDS','kb|g.166819.CDS.713'), ('gene','kb|g.166819.locus.886')],
                },
            '-': 
                {'1010461-1010670': [('mRNA','kb|g.166819.mRNA.61')],
                }
            }
        }
    }

This way, no matter what the structure of the get_feature_ids() output is, the lists that are the leaf values can always be used as input to get_features(), without needing to munge the values in the list.

Any objections to what I've written?

**Comment by kkellerlbl** [comment]
I will be updating the Thrift specs to reflect our talk and my summary above.

**Comment by realmarcin** [comment]
The balance is low complexity return vs being able to make complex queries
for features. This is becoming hard so realistically we will need higher
level methods on top of this anyway.

Still, getting all ids and features for a single contig is a standard
operation and that return does look pretty complex now because the return
will be three deep: by_region, contig_id, and region coordinates. Is that
right? Imagine we are asking for all mRNAs from a contig (in this example
from a small region)

{'by_region':
    {'kb|g.166819.c.0':
            {'1002883-1004221': [ ('mRNA', 'kb|g.166819.mRNA.743')]
            }
    }
}

However, since the main use of this method for now is supplying inputs to
other methods, its really more of matter of making the other methods
compatible. I think soon we will need another version of get_feature_ids
which just returns a list of ids.


Also, I'm worried about feature ids here again. Are the 'gene' values going
into get_features() of the type 'kb|g.166819.mRNA.743', that is they are
fully qualified?

A little disconcerting that the CDS and mRNA ids do not match -- they won't
match exactly due to alternative splicing but the euk convention is
generally id.1, id.2 for two different mRNA/cds originating from the same
genomic locus.

Finally, what specific CDS and mRNA ids are we suggesting that developers
use in their code? Since the original ids in different containers
overlapped it should be something like the fully qualified ids.


p.s. We still have '|' in KBase ids??? I thought this was our chance to
improve ...

**Comment by kkellerlbl** [comment]
This PR is not meant to address the structure of the return value when using group_by=region.  The only change there is that the list of features is now becoming a list of feature tuples.

The input to get_features() will be a list of feature tuples (instead of a list of feature ids, as it is now).  So you might call

    result = api.get_features( [ ('gene','geneid1') , ('CDS','cdsid2'), ('all', 'featureid3') ] )

**Comment by kkellerlbl** [comment]
In the thrift spec I called the new type "Feature_tuple" but I am not tied to that label.

**Comment by realmarcin** [comment]
OK, but this is a really near term fix in my mind -- the fact that we need
this reveals a data modeling flaw.

Going forward we can't solve this with fully qualified ids? That sounds
like the right long term solution. Having redundant ids is not just a
problem for the data API -- how will people know which id they are
referring to in their code?



On Thu, Dec 10, 2015 at 4:19 PM, kkellerlbl <notifications@github.com>
wrote:

> This PR is not meant to address the structure of the return value when
> using group_by=region. The only change there is that the list of features
> is now becoming a list of feature tuples. The input to get_features() will
> be a list of feature tuples
>
feature id tuples to be exact -- as long as the arg data is exactly
provided by other methods (eg get_feature_ids) we are good. otherwise there
are dependent changes worth making.

**Comment by kkellerlbl** [comment]
I think all of the issues you bring up are out of scope for the work on this PR, which is really meant as a fix for bug KBASE-3172.

**Comment by realmarcin** [comment]
Fine by me.

**Comment by kkellerlbl** [comment]
I will be adding a very large commit which is the Thrift libs generated from the new spec by 0.9.3.  Please do not merge this PR!  It is definitely not ready.  (I can close it if people think there is a risk of accidentally merging, but I'd like to leave it open so you can watch my progress.)

**Comment by kkellerlbl** [comment]
I just made some commits for get_feature_ids(), but the work is still in progress, and I'm pretty sure tests will fail.  Please don't merge, but read and comment if you have questions or objections so far.

**Comment by kkellerlbl** [comment]
As we mentioned in Slack and on our standup, there is a possibility that other methods may need to be updated to accept a list of tuples of ('feature_type','feature_id') as input.  I'm hoping to fix get_features() in this PR, then make new PRs for other methods that need to change (even though there would be spec changes for those).

**Comment by kkellerlbl** [comment]
Also, I will probably need to fix the tests, since it's likely they will currently fail.

**Comment by kkellerlbl** [comment]
I just made a new commit for get_features.  I checked the kbase/develop version of get_features, and it also emits a Region Thrift object instead of a generic dict() for the feature locations.  That's not fabulous, but at least my changes didn't break anything that was working before.

There are still no tests (or tests are broken) and I still need to look at the example Jason found to see whether my changes actually fix the problem (which was the whole point, after all).

**Comment by kkellerlbl** [comment]
I just added some code to api.py as what I hope is the final changes needed for get_features().  I still expect tests to fail, but if by some miracle they pass, please do not merge, as I would like to make sure that the tests are actually testing the right things.

**Comment by mlhenderson** [comment]
Keith, we're basically dumping the feature tuples because it just leads to complications, but you have things in here which are not related.  I will go through your changes compared to the kbase/develop branch to see what we can keep.  In hindsight we should have discussed the feature tuples more before going in that direction, and this was on me for not being able to spend more time when this came up.

**Comment by kkellerlbl** [comment]
Ok, sounds good.  I thought I tried to minimize how much non-get_features() code snuck in but maybe I missed some.  I hope it's not very much.

This will also impact the PR for the perl_clients code; it's worse there because I was less careful about separating out the code.  I'll browse the diffs and see what might be impacted.

**Comment by mlhenderson** [comment]
Ok, I'm going to close this since we ended up not going down this route.

**Pull request closed without merging**
