### PR TITLE
adding genome related api code

### PR DESCRIPTION
**Pull request by mlhenderson**
Some prototype code for an API library that works on genome annotations, assemblies, taxons.
This code works against two different type varieties, the current Genome object types and a new set that we want to validate, both of which will be abstracted behind these API methods so that developers can code against the API and not need to have deep knowledge of how the type information is structured or embed that knowledge in various pieces of our codebase.

There is a top level README.md that has instructions for getting the code installed.  Since this is a prototype, many things are subject to change in the design.

### CODE REVIEW

**Comment by dangunter** [comment]
Can we get some tests running in TravisCI?

**Comment by mlhenderson** [comment]
At the moment all the tests rely on having a kbase auth token.  There are
tests of course, but they are not yet connected to travis and if you were
to try to run them now they would fail.

**Comment by dangunter** [comment]
OK. I would say getting some tests should be high priority. We should do mocks or local MongoDB (TravisCI has one) to get it running. But we need to get going, so I'll look at code now.

**Comment by dangunter** [comment]
So, the code looks close enough. I don't know if any of it works, but since  Matt claims it does I'll take his word for it. The style of comments is not exactly correct (see Google Python Style, which is what this is imitating, I believe) and this may make generating docs a pain even with the napoleon Sphinx plugin.

**Comment by mlhenderson** [comment]
You can actually verify that at least basic tests work without too much
effort, just not using TravisCI.

**Comment by mlhenderson** [comment]
Yes, it is pseudo Google docstring style.  We can change that, I don't have
a strong preference.

**Comment by dangunter** [comment]
I think you need better module level documentation

In [3]: assembly?
Type:        module
String form: <module 'biokbase.data_api.assembly' from '/Users/dang/.virtualenvs/kbase_data_api/lib/python2.7/site-packages/genome_api-0.1-py2.7.egg/biokbase/data_api/assembly.pyc'>
File:        ~/.virtualenvs/kbase_data_api/lib/python2.7/site-packages/genome_api-0.1-py2.7.egg/biokbase/data_api/assembly.py
Docstring:   <no docstring>

it would be really helpful if each module provided an overview of the functions

**Pull request merged**
