### PR TITLE
fixing genome annotation data api service url in deployment.cfg

### PR DESCRIPTION
**Pull request by mlhenderson**

### CODE REVIEW

**Comment by mlhenderson** [comment]
@kkellerlbl Look correct to you?

**Comment by kkellerlbl** [comment]
Looks okay to me, I can merge if you like.

**Comment by mlhenderson** [comment]
Great, yeah let's merge this so the configs are correct on redeploy.

**Comment by kkellerlbl** [comment]
Actually, I should back up: is that the endpoint that you want?  If you prefer genome_annotation I can update the deploy config instead.

**Comment by mlhenderson** [comment]
Oh I get choices!  I think genome_annotation would be more future proof.
If we do that we can just close this PR, no problem there.

**Comment by kkellerlbl** [comment]
You can have /services/data/mattsawesometype/rulestheworld if you like!

I'll make the change on -ci now.  The -next proxy is still unconfigured but when I get to it I'll have it be genome_annotation too.

**Comment by kkellerlbl** [comment]
If you want to change either of the others now's the time!

**Comment by mlhenderson** [comment]
I think taxon and assembly are good for now.  Thanks Keith.

**Comment by kkellerlbl** [comment]
Okay.  The next -ci deploy should pick up the new endpoint.  I'm modifying the check_mk check as well.

**Comment by kkellerlbl** [comment]
check_mk mods in PR 167.

**Pull request closed without merging**
