### PR TITLE
Create plot_genome_data.ipynb

### PR DESCRIPTION
**Pull request by realmarcin**

### CODE REVIEW

**Comment by mlhenderson** [comment]
This is meant to be a sketch of a data quality panel that we could add to the genome landing page.

There are 4 plots included in this notebook, Contig GC% vs Contig position, Contig GC% vs Contig Length, Contig GC% vs log10 Contig Length, and then a distribution plot of Cumulative GC%.


kb g 3157

**Comment by mlhenderson** [comment]
Looking for feedback on contents for genome landing page data quality summary panel, @samseaver @briehl @aparkin @psdehal.  Marcin is working on some plots using the data_api.  I'd like to make sure we have something useful for microbes and plants at least.  Marcin can submit new plot screens here as he makes updates.

**Comment by realmarcin** [comment]
Attached is a screenshot for the latest version of this notebook. I'm still
testing  which plots might work with which data but the idea is to generate
a set of plots from which we can make selections. The bottom right
histogram has a strange y-axis for still unknown reasons and there are more
upgrades in the works.


[image: Inline image 2]

**Comment by samseaver** [comment]
It didn't seem like the new screenshot appeared correctly

**Comment by aparkin** [comment]
I didn't see the graphics either. Do you have a mock-up of the entire page yet?
There are key tables we would want for different genome types of course. 
There are the basic functional enrichments. 
Measurements of goodness of annotation (number of specifically annotated genes, etc. etc. with possible inkage to supporting data). 
Some depiction of the replicons and their key properties (including location... eg. K. lactis has a nuclear genome and a cytoplasmic plasmid with an orthogonal replication system). 
Something about quality and closure of sequence. 
...

**Comment by realmarcin** [comment]
Thanks, Adam -- there is no mockup, but my understanding is we will be
working off of the existing genome landing page. We have looked at the
ENSEMBL genome page design and it has most of the details you list and
more. My only comment for now is that we are working with the data which is
available in current genome objects. I think the hope is that future KBase
reference genome uploads will have more data. Your suggestions may help
prioritize which data to collect or create, even if only with the data API.

Strange about the graphic -- there is no attachment or graphic is blank?

It is showing in my gmail email thread and I am attaching the image I
downloaded from the thread.
Maybe its some file extension issue? Just in case I renamed the extension
to .pnge so if this does work then you'll have to rename.
I also attached one with a different file name in case that was the problem
...

If all that fails there's google drive:
https://drive.google.com/file/d/0Bw1H97l186NEbkRnRVI2M0tqaFk/view?usp=sharing


[image: Inline image 2]Screen Shot 2015-09-19 at 12.45.21 AM.png


[image: Inline image 1]

**Comment by mlhenderson** [comment]
@realmarcin to have the screenshots with plots appear in the github PR you can drag and drop the image into a comment.

**Comment by mlhenderson** [comment]
screenshot2015-09-19

**Comment by realmarcin** [comment]
good idea, thanks

**Comment by mlhenderson** [comment]
@aparkin the specific goal here is to sketch out and determine an additional panel to add to the genome landing page that provides a data quality summary.  I would like to determine what that content *should* be independent of what we actually have in the objects today.  It may be that there is a difference between what should be there vs what we have, and then at that point we may not be able to provide all of that today, but we could work towards the full content.  So far the plots Marcin has worked on are oriented around the assembled contig sequences, as you mentioned some quality measures of the annotation of the sequence is also important to have.  I would like to make sure we're getting the content right here.

**Comment by mlhenderson** [comment]
@samseaver @aparkin can you give a thumbs up/thumbs down to each of the plots marcin is proposing for the data quality panel?  Basically you're seeing his sketch so far.  If the content is way off, please make suggestions and/or direct him to literature or examples that would be constructive for data quality of microbial and eukaryotic assembly and microbial and eukaryotic annotation.

Marcin is working on a plot showing numbers of features per contig.

**Comment by realmarcin** [comment]
Now with the Nx plot. The last missing piece is reflecting the contig length steps in the percentiles.

screen shot 2015-09-25 at 1 05 50 am

**Comment by realmarcin** [comment]
screen shot 2015-09-25 at 12 09 15 pm

**Comment by realmarcin** [comment]
Its not the full screenshot because my jupyter output panel is misbehaving again.

There are still issues with two histogram scales.

screen shot 2015-09-26 at 12 46 10 am

**Comment by mschatz** [comment]
These are nice summaries for the assemblies. Is there a maximum number of contigs that can be evaluated? I only ask because some of the draft eukaryotic or metagenomic assemblies can have many tens to hundreds of thousands of sequences (or more). Note these displays are also useful for comparing different assemblies, such as to overlay multiple curves in a single Nx plot. For example, see figure 2b here: http://www.pnas.org/content/early/2015/09/15/1516718112.full.pdf

**Comment by realmarcin** [comment]
Thanks for the feedback, its really appreciated.

Yes, there is an upper limit and we don't have a hard number yet, but my
gut says things will start breaking down around 10E6 data points. We have
tried generating these plots in series for many genomes and things stop
after a few large eukaryotic ones because of browser memory limits. For
those extreme datasets we may need a different strategy such as serving a
static image from a KBase service. However, these things are hard for
everyone and there are some real problems there.

For the multiple comparison ideas -- yes, that's in the plans. Many of
these plots could show multiple assemblies, with some redesign. This will
become more powerful when performance of the API is optimized and when more
genomes and assemblies are available as new objects.

In the future sometime there will be a focus on assemblies and reads as
well, and that will allow to plug in to all the per-base quality measures.

**Comment by mlhenderson** [comment]
Marcin, let's get this notebook in the develop branch.  We also have it in the CI Narrative, but I would like to also see it checked in.

**Comment by mlhenderson** [comment]
@realmarcin when you are not busy with something else, switch the target of this PR to develop so we can get it merged.  At the time we were working off of master, so it makes sense that it originally was going there.  I was hoping for more feedback but that didn't show, so we'll just get this in and move on.

**Comment by realmarcin** [comment]
OK, thanks.

**Comment by realmarcin** [comment]
For switching the target branch, it looks like I need reclone and move over
my changes?
I checked and my current fork has no develop branch listed on github, so
perhaps it was created after I cloned.

**Comment by mlhenderson** [comment]
If you set up the remote upstream, you can git fetch upstream, then that
will pick up the develop branch.
At that point you just need to commit that file to your local develop
branch and submit a PR to data_api:develop and we can merge it in.

You should not need to refork.

**Comment by realmarcin** [comment]
Great, thanks!

**Comment by mlhenderson** [comment]
Ok, this notebook has been merged into the develop branch, closing this PR.

**Pull request closed without merging**
