### PR TITLE
The docxorcist: scariest doc PR ever

### PR DESCRIPTION
**Pull request by dangunter**
Got JavaScript docs to look half-decent, made Python docs more self-similar, switched to "read the docs" theme

* commented the bleep out of the .thrift files
* improved the script that generates .rst docs for Sphinx from that
* considered factoring out exceptions and using Thrift "include", but this created all sorts of other issues, so backed out of that (some minor changes to setup.py as a result, nothing truly different)
* Generated docs pushed to the [Data API page on github.io](http://kbase.github.io/docs-ghpages/docs/data_api/index.html)

For next PR, will get the Perl docs in good shape too. Most of the way there, just need to refactor the generator module to create Perl syntax examples and signatures in the API ref. Java would be the same idea, so not too far from autodoc. for all the clients (off the comments in the Thrift), except Python of course which is "special".

### CODE REVIEW

**Comment by mlhenderson** [comment]
:imp: :feelsgood:

We still need to reconcile the javascript code with the docs, because we have some inconsistencies there.

**Comment by mlhenderson** [comment]
Did you mean to disable redis in deployment.cfg?

**Comment by dangunter** [comment]
Oh, no, that was the by-product of some redis question earlier. I can put that back. Good catch.

**Comment by dangunter** [comment]
re: the javascript code, I agree but to be clear I think the code should be modified to be like the docs, not the other way around (mostly get_foo() instead of plain foo()). Did you have anything else in mind?

**Comment by mlhenderson** [comment]
That was what I was referring to, updating the js code to be consistent with the docs and the other api code.  That isn't in this repo actually, just noting that we need to fix that.

**Pull request merged**
