### PR TITLE
Taxon upload changes and changes to the spec

### PR DESCRIPTION
**Pull request by jkbaumohl**

### CODE REVIEW

**Comment by mlhenderson** [comment]
What prompted the change to biokbase?

**Comment by jkbaumohl** [comment]
It did not work with doekbase (which was the original code)

**Comment by mlhenderson** [comment]
Ok, well let's find out why it did not work with doekbase and fix that.  In this repo, you should fully expect the doekbase module to work.  Can you write a test that demonstrates that it does not work?

**Comment by jkbaumohl** [comment]
jkbaumohl@dev01:~/data_api/data_loading/genome_loading$ python
make_taxons_lookup_doe.py --wsname ReferenceTaxons --wsurl
https://next.kbase.us/services/ws --taxon_
names_file ~/data_api/taxonomy_uploading/names.dmp >
taxon_lookup_output_doe

Traceback (most recent call last):
  File "make_taxons_lookup_doe.py", line 15, in <module>
    import doekbase.workspace.client
ImportError: No module named doekbase.workspace.client

**Comment by mlhenderson** [comment]
So you would need to be using an install of data_api.  This is critical for
doing development using the api.

**Comment by jkbaumohl** [comment]
Do you mean running a virtual environment?
Not sure what you mean by this.

**Comment by realmarcin** [comment]
yes, Matt means you need to install the data_api into a local venv.

there are detailed instructions in the README.md for the data_api repo,
good place to start.

**Comment by jkbaumohl** [comment]
We tried this last Friday and it failed.

**Comment by jkbaumohl** [comment]
Tried again, still failing.  Not sure what to do.  I know this was set up
to make it "easy", but it never has been for me.

**Comment by realmarcin** [comment]
there was some message about 'darwin' in Jason's errors -- he can post the
error here. that made me think that there is a PC install issue ...

**Comment by jkbaumohl** [comment]
(venv)jkbaumohl@dev01:~/data_api$ python setup.py install
.
.
.

Writing /tmp/easy_install-c9no6j/ipython-4.1.1/setup.cfg
Running ipython-4.1.1/setup.py -q bdist_egg --dist-dir
/tmp/easy_install-c9no6j/ipython-4.1.1/egg-dist-tmp-sCCBEO
error: Setup script exited with error in ipython setup command: Invalid
environment marker: sys_platform == "darwin" and
platform_python_implementation == "CPython"

**Pull request merged**
