### PR TITLE
[WIP] notebook generating functional GenBank file

### PR DESCRIPTION
**Pull request by realmarcin**
I would still like to store the final version of the notebook (without result cells) somewhere in the repo.

Also, here is an example Genbank file generated with the notebook code:
[628.gbk.zip](https://github.com/kbase/data_api/files/298726/628.gbk.zip)

### CODE REVIEW

**Comment by realmarcin** [comment]
TODO
- no function
- handle non-gene/CDS/mRNA features
- sort features by location
- get contig data
- write contig data (method in place)
- pull direct genbank file

**Comment by realmarcin** [comment]
Also seeing these errors from the travis:

# 

## ERROR: test_start_service (lib.doekbase.data_api.tests.test_service_core.TestStartService)

Traceback (most recent call last):
  File "/home/travis/build/kbase/data_api/lib/doekbase/data_api/tests/test_service_core.py", line 129, in test_start_service
    internet.reactor.callWhenRunning(sc.stop_service)

# AttributeError: 'module' object has no attribute 'reactor'

## ERROR: test_start_service_twisted_exception (lib.doekbase.data_api.tests.test_service_core.TestStartService)

Traceback (most recent call last):
  File "/home/travis/build/kbase/data_api/lib/doekbase/data_api/tests/test_service_core.py", line 141, in test_start_service_twisted_exception
    orig_reactor = sc.twisted.internet.reactor
AttributeError: 'module' object has no attribute 'reactor'

**Comment by mlhenderson** [comment]
@realmarcin This PR should be against develop, right?

**Comment by realmarcin** [comment]
yes, this was WIP -- I can close this PR and we only need to worry about one against develop

**Pull request closed without merging**
