### PR TITLE
Changes for Perl clients, check_mk, travis builds

### PR DESCRIPTION
**Pull request by kkellerlbl**
The major change here is the Thrift namespace; previously the namespace was a wildcard for all languages.  I've specified namespaces for Python, JavaScript, and Perl explicitly.

There are also changes for check_mk and Travis, notably checking for the KB_AUTH_TOKEN environment variable, and passing '' if it doesn't exist.  This lets the scripts run in Travis (or any environment with the test_resources backing store) without a token.

### CODE REVIEW

**Comment by kkellerlbl** [comment]
I don't see my Thrift changes here, I must have forgotten to push them.  Please don't merge yet.

**Comment by kkellerlbl** [comment]
Ok, I have my thrift changes in now.  Please review and leave me comments, or if there are no problems merge after Travis succeeds.

**Comment by mlhenderson** [comment]
It looks like test_api_service does not have an entry for genome_annotation yet.  We also probably need to regenerate and commit the perl thrift clients to pick up the namespace changes.  We can do that in this PR, or I can do that after this is merged.

For data_api_service, was the idea to test with assembly first and then add the others later?

**Comment by kkellerlbl** [comment]
Let's merge first, then regenerate.  Does that sound okay?

Yes, test_api_service only supports assembly at the moment.  I'd rather just get the commit in now, and add support for taxon and annotation later (perhaps this week or next).  The data_api_service changes will follow test_api_service; when I add support for other services I'll add them to data_api_service.

**Comment by mlhenderson** [comment]
Ok, merging.

**Pull request merged**
