### PR TITLE
some mocking up of the interfaces

### PR DESCRIPTION
**Pull request by dangunter**
Mocked up some object interfaces, in the context (for starters) of what it would take to load a file into the system. Maybe for anyone else, the only thing of interest would be the little ASCII art class diagram around line 120 of kbase_data.py

### CODE REVIEW

**Comment by mlhenderson** [comment]
@dangunter Interesting, we should try this with some use cases.  I'm going to ignore the coverage and not be too picky because we're just trying to get some alpha code up.  I'll give it some more time to air out in case anyone else wants to chime in about this before merging.

**Comment by dangunter** [comment]
@mlhenderson thanks, and frickin'a I finally got the py3.x build to pass. I realize it's not really a big deal, but we should get in the habit, yes?

**Comment by mlhenderson** [comment]
@dangunter yes, we should be doing our best not to reduce testing coverage.

**Comment by mlhenderson** [comment]
Thanks, merging now.

**Pull request merged**
