### PR TITLE
example narrative link in README + intermediate example notebook fixes

### PR DESCRIPTION
**Pull request by realmarcin**

### CODE REVIEW

**Comment by dangunter** [comment]
Please fix import errors so the tests pass

**Comment by realmarcin** [comment]
They are failing on the example data.

Really for this PR we just want the README. The rest are intermediate test example (not example nbs) nb fixes developed in jupyter, not ready for noses tests yet. Let me know if you have ideas of how to proceed.

The problem is that we have two sets of notebooks, and one set is in backlog. The backlog ones have the errors. Perhaps it's a good moment to move somewhere else.

Do I need a new fork and then manual copy of README? May be the easiest ...

**Comment by dangunter** [comment]
yes you should make a different branch for this change. Or just edit the develop branch README in github. There is another problem, though, in that the Narrative itself is not descriptive of what is being done, or what any of it means. So I think the first priority is to fix that.

**Comment by dangunter** [comment]
will not merge -- README fix went in another PR

**Pull request closed without merging**
