### PR TITLE
Refactoring Marcin's FASTA file creation example

### PR DESCRIPTION
**Pull request by dangunter**
JIRA KBASE-3037:

### CODE REVIEW

**Comment by realmarcin** [comment]
OK, thanks. The protein_to_fasta test suceeded while the GFF example had
some import problems.

I'm vague on what was not working (aside from the import I reported on
Friday for the GFF example) -- and what you did to fix it ...  Well, you
probably didn't fix that one problem I was aware of because it has no edits
in the commit :)

The major change seems to be adding the example directly to
genome_annotation_api.py

which originally did a test more like my GFF example. The GFF example is
actually a better test of multiple related API methods and the underlying
data structure, so my thinking is we actually want to keep that one (or a
modified version of it, perhaps based on my new GFF example). Also my
understanding was that all files with prefix 'test_' were run as part of
the global test but now its unclear whether I should be adding more
examples named with test_.


And you prefer the collapsed style of function calls? Its harder to test
and not really great practice I thought ;)

temp_files.append(proteins_to_fasta(url))

**Comment by dangunter** [comment]
@realmarcin, you were not setting up the WS URL using the 'shared' module and you stuck run() at the top level of the file so it ran on import. we can keep GFF but I wasn't sure what it was doing so I commented it out for now. 

I feel it's easier to just have one set of examples per API, since that is how they are going to be included into the docs (see docs/annotation_api.rst). So, as I did with taxon I made it into a function inside the most appropriate API file.

**Comment by realmarcin** [comment]
On Mon, Nov 9, 2015 at 6:09 PM, Dan Gunter <notifications@github.com> wrote:

> @realmarcin <https://github.com/realmarcin>, you were not setting up the
> WS URL using the 'shared' module and you stuck run() at the top level of
> the file so it ran on import. we can keep GFF but I wasn't sure what it was
> doing so I commented it out for now.
>
Fine by me -- note that the fasta dump limits it to three proteins.

> I feel it's easier to just have one set of examples per API, since that is
> how they are going to be included into the docs (see
> docs/annotation_api.rst). So, as I did with taxon I made it into a function
> inside the most appropriate API file.
>

OK but now if I add other examples, which I'm developing as a separate
scripts, it would be added to the monolithic test code? Somewhere else? Or
do you mean just a single example per API period? I discussed additional
examples with Matt, particularly ones that used multiple method calls and
APIs. Let me know if we have any naming/structuring preferences there.

**Comment by realmarcin** [comment]
I think there is some confusion -- we are looking at different files
or versions. It looks like something happened with the PRs. I
submitted PR 104 which was closed due to being against master -- but
then I made a new PR against develop and it sounded like Keith saw
that (on slack). Also it looks like PR 102 is still open -- I'll
repost this puzzle on slack.


Also I didn't create genome_annotation_api.py or
test_genome_annotation_api.py. And the two examples I PRed didn't have
the issues you listed below (note that the GFF example test isn't
committed yet).

> @realmarcin, you were not setting up the WS URL using the 'shared' module

I mirrored the Taxon API example exactly -- so whatever shared module
use there was, is there:

###test_proteins_to_fasta.py
def setup():
    shared.setup()

def test_examples():
    url = shared.services['workspace_service_url']
    proteins_to_fasta.run()


>
> and you stuck run() at the top level of the file so it ran on import.

Do you mean in proteins_to_fasta.py?
This is the end of that file (in the GFF example i also have the
execution code at the end of the file):

def run():

genomeref = "PrototypeReferenceGenomes/kb|g.3899"

genome = ObjectAPI(services, token=token, ref=genomeref)

genome_annotation = GenomeAnnotationAPI(services, token, ref=genomeref)


proteins= genome_annotation.get_proteins()

fasta = get_protein_fasta(proteins)


outfile = '3899_prot.fasta'

print outfile

with open(outfile, 'w') as f:

f.write(fasta)



run()



> we can keep GFF but I wasn't sure what it was doing so I commented it out for now.


git history shows you were the last editor of

genome_annotation_api.py

**Pull request merged**
